#************************************************************* ## ECE 344L - Microprocessors - Spring 2015## Name: Matthew James Greci##     Laboratory Number: 3             Due Date: 2 April 2015### Lab Group: N/A### #*************************************************************** ## This is the config file needed to run Interrupts and UART.# #***************************************************************
.section .config_BFC02FF4,code
.word 0xfff8ffd9

.section .config_BFC02FF8,code
.word 0xFFFFFCFB
